global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'hl7_services'
    static_configs:
      - targets:
          - 'producer:8000'
          - 'consumer:8000'
          - 'validator:8000'
          - 'fhir-transformer:8000'