[tool.black]
line-length = 99
target-version = ['py312']

[tool.autohooks]
mode = "pythonpath"
pre-commit = ["autohooks.plugins.black", "autohooks.plugins.ruff", "autohooks.plugins.isort"]

[tool.isort]
profile = "black"
known_first_party = [
    "metrics",
    "common",
    "generators",
    "decorators",
    "utils",
]

[tool.ruff]
fix = true
lint.select = ["F401"]
line-length = 99