[tool.black]
line-length = 99
target-version = ['py312']

[tool.autohooks]
mode = "pythonpath"
pre-commit = ["autohooks.plugins.black", "autohooks.plugins.ruff.format", "autohooks.plugins.isort"]

[tool.isort]
profile = "black"