{
 "title": "HL7 to FHIR Pipeline Performance Metrics",
 "description": "Metrics related to the performance of my HL7 -> FHIR pipeline. Metrics are focused on surfacing anomalies and bottlenecks.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "No. of Messages Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(messages_received_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "No. of Messages Accepted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(messages_accepted_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "No. of Messages Converted to FHIR",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(messages_accepted_total) - (sum(fhir_conversion_failed_total) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (message_type) (rate(messages_sent_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validation & QA",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (details) (validation_error_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Ingest Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (message_type) (rate(messages_received_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ADT_A01 Processing Time (sec.) by Stage",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, stage) (rate(hl7_stage_duration_seconds_bucket{message_type=\"ADT_A01\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ADT_A03 Processing Time (sec.) by Stage",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, stage) (rate(hl7_stage_duration_seconds_bucket{message_type=\"ADT_A03\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FHIR Conversion Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(sum by (message_type) (rate(fhir_conversion_failed_total[1m])) / clamp_min(sum by (stage, message_type) (rate(fhir_conversion_attempted_total[1m])), 1e-9))\nor on (message_type)\n(0 * sum by (message_type) (rate(fhir_conversion_attempted_total[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}