from hl7_segment_generators import (
    generate_evn_segment,
    generate_msh_segment,
    generate_pid_segment,
    generate_pv1_segment,
)

# if a segment's identifier is None then the segment is a segment group.
MESSAGE_REGISTRY = {
    "ADT_A01": {
        "segments": [
            {
                "name": "Message Segment Header",
                "identifier": "MSH",
                "required": True,
                "repeatable": False,
                "generator": generate_msh_segment,
            },
            {
                "name": "Event Type",
                "identifier": "EVN",
                "required": True,
                "repeatable": False,
                "generator": generate_evn_segment,
            },
            {
                "name": "Patient Identifier",
                "identifier": "PID",
                "required": True,
                "repeatable": False,
                "generator": generate_pid_segment,
            },
            {
                "name": "Patient Demographic",
                "identifier": "PD1",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
            {
                "name": "Next of Kin",
                "identifier": "NK1",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
            {
                "name": "Patient Visit",
                "identifier": "PV1",
                "required": True,
                "repeatable": False,
                "generator": generate_pv1_segment,
            },
            {
                "name": "Patient Visit - Additional Information",
                "identifier": "PV2",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
            {
                "name": "Disability Segment",
                "identifier": "DB1",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
            {
                "name": "Observation Segment",
                "identifier": "OBX",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
            {
                "name": "Patient Allergy Information",
                "identifier": "AL1",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
            {
                "name": "Diagnosis",
                "identifier": "DG1",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
            {
                "name": "Diagnosis Related Group",
                "identifier": "DRG",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
            {
                "name": "Procedure",
                "identifier": None,
                "required": False,
                "repeatable": True,
                "segments": [
                    {
                        "name": "Procedures",
                        "identifier": "PR1",
                        "required": True,
                        "repeatable": False,
                        "generator": None,
                    },
                    {
                        "name": "Role",
                        "identifier": "ROL",
                        "required": False,
                        "repeatable": True,
                        "generator": None,
                    },
                ],
            },
            {
                "name": "Guarantor",
                "identifier": "GT1",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
            {
                "name": "Insurance",
                "identifier": None,
                "required": False,
                "repeatable": True,
                "segments": [
                    {
                        "name": "Insurance",
                        "identifier": "IN1",
                        "required": True,
                        "repeatable": False,
                        "generator": None,
                    },
                    {
                        "name": "Insurance - Additional Information",
                        "identifier": "IN2",
                        "required": False,
                        "repeatable": False,
                        "generator": None,
                    },
                    {
                        "name": "Insurance - Additional Information - Certification",
                        "identifier": "IN3",
                        "required": False,
                        "repeatable": False,
                        "generator": None,
                    },
                ],
            },
            {
                "name": "Accident",
                "identifier": "ACC",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
            {
                "name": "UB82 Data",
                "identifier": "UB1",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
            {
                "name": "UB92 Data",
                "identifier": "UB2",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
        ]
    },
    "ADT_A03": {
        "segments": [
            {
                "name": "Message Segment Header",
                "identifier": "MSH",
                "required": True,
                "repeatable": False,
                "generator": generate_msh_segment,
            },
            {
                "name": "Event Type",
                "identifier": "EVN",
                "required": True,
                "repeatable": False,
                "generator": generate_evn_segment,
            },
            {
                "name": "Patient Identification",
                "identifier": "PID",
                "required": True,
                "repeatable": False,
                "generator": generate_pid_segment,
            },
            {
                "name": "Patient Demographic",
                "identifier": "PD1",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
            {
                "name": "Patient Visit",
                "identifier": "PV1",
                "required": True,
                "repeatable": False,
                "generator": generate_pv1_segment,
            },
            {
                "name": "Patient Visit - Additional Information",
                "identifier": "PV2",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
            {
                "name": "Disability Segment",
                "identifier": "DB1",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
            {
                "name": "Diagnosis",
                "identifier": "DG1",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
            {
                "name": "Diagnosis Related Group",
                "identifier": "DRG",
                "required": False,
                "repeatable": False,
                "generator": None,
            },
            {
                "name": "Procedure",
                "identifier": None,
                "required": False,
                "repeatable": True,
                "segments": [
                    {
                        "name": "Procedures",
                        "identifier": "PR1",
                        "required": True,
                        "repeatable": False,
                        "generator": None,
                    },
                    {
                        "name": "Role",
                        "identifier": "ROL",
                        "required": False,
                        "repeatable": True,
                        "generator": None,
                    },
                ],
            },
            {
                "name": "Observation Segment",
                "identifier": "OBX",
                "required": False,
                "repeatable": True,
                "generator": None,
            },
        ],
    },
}
